version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 639993312576.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=639993312576.dkr.ecr.us-east-2.amazonaws.com/flask-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-250)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t flask-app .
      - docker tag flask-app:latest 639993312576.dkr.ecr.us-east-2.amazonaws.com/flask-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 639993312576.dkr.ecr.us-east-2.amazonaws.com/python-code:latest
      - echo Writing image definitions file...
      - printf '[{"name":"flask-app","imageUri":"%s"}]' 639993312576.dkr.ecr.us-east-2.amazonaws.com/flask-app:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
